### ISSUE TITLE
[Closed]Hmmm, i do somethink wrong?

### ISSUE THREAD

**Issue by Ningaro** [spotify/web-api-auth-examples#23]
```
C:\Users\Ningaro\Documents\GitHub\web-api-auth-examples-master\authorization_code>powershell -file powshell.ps1
module.js:557
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Ningaro\Documents\GitHub\web-api-auth-examples-master\authorization_code\app.js:10:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

```

_Windows 10 x64
Node.JS 9.4.0_

**Comment by Ningaro** [comment]
use `npm install` in same folder, and all started working

**Comment by LeisGee** [comment]
Had the same problem, it was caused by another Javascript file that was still running with node.js.
