### ISSUE TITLE
 Need help

### ISSUE THREAD

**Issue by tiree24** [spotify/web-api-auth-examples#56]
when I do a node auth.js this pops up

internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '/Users/tireejackson/Documents/backend_repo/auth.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by hugorila** [comment]
Hello,

Maybe this is happening because you don't have the node installed on your computer. 

Try to download and install it https://nodejs.org/en/
